apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: rubyontailsapp-template
objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: null
    finalizers:
    - kubernetes.io/pvc-protection
    name: drkiq-postgres
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: pv0074
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
    creationTimestamp: null
    finalizers:
    - kubernetes.io/pvc-protection
    name: drkiq-redis
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: pv0099
  status: {}
- apiVersion: v1
  data:
    password: eW91cnBhc3N3b3Jk
    username: ZHJraXE=
  kind: Secret
  metadata:
    creationTimestamp: null
    name: pg-secret
  type: Opaque
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 19
    labels:
      app: drkiq
    name: drkiq
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: drkiq
      deploymentconfig: drkiq
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: drkiq
          deploymentconfig: drkiq
      spec:
        containers:
        - env:
          - name: CACHE_URL
            valueFrom:
              configMapKeyRef:
                key: CACHE_URL
                name: drkiq.env
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                key: DATABASE_URL
                name: drkiq.env
          - name: JOB_WORER_URL
            valueFrom:
              configMapKeyRef:
                key: JOB_WORKER_URL
                name: drkiq.env
          - name: LISTEN_ON
            valueFrom:
              configMapKeyRef:
                key: LISTEN_ON
                name: drkiq.env
          - name: SECRET_TOKEN
            valueFrom:
              configMapKeyRef:
                key: SECRET_TOKEN
                name: drkiq.env
          - name: WORKER_PROCESSES
            valueFrom:
              configMapKeyRef:
                key: WORKER_PROCESSES
                name: drkiq.env
          image: 172.30.1.1:5000/myproject/drkiq@sha256:c4a5968a8e6b7754862cf11392d627b0449e75e4b3d259382a9a50605bdfa452
          imagePullPolicy: Always
          name: drkiq
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8000
            timeoutSeconds: 15
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /drkiq/public
            name: drkiq-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: drkiq-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - drkiq
        from:
          kind: ImageStreamTag
          name: drkiq:latest
          namespace: myproject
        lastTriggeredImage: 172.30.1.1:5000/myproject/drkiq@sha256:c4a5968a8e6b7754862cf11392d627b0449e75e4b3d259382a9a50605bdfa452
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 16
    labels:
      app: postgresql-96-rhel7
    name: postgresql-96-rhel7
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: postgresql-96-rhel7
      deploymentconfig: postgresql-96-rhel7
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: postgresql-96-rhel7
          deploymentconfig: postgresql-96-rhel7
      spec:
        containers:
        - env:
          - name: POSTGRESQL_DATABASE
            value: drkiq_development
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: pg-secret
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: pg-secret
          image: registry.access.redhat.com/rhscl/postgresql-96-rhel7@sha256:62a42216cb66e00cfcc66a28a6fb9a9953f2aed8592c4fd5140ddfa5b2193193
          imagePullPolicy: Always
          name: postgresql-96-rhel7
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5432
            timeoutSeconds: 5
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: postgresql-96-rhel7-volume-1
          - mountPath: /var/lib/postgresql
            name: drkiq-postgres
            subPath: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: postgresql-96-rhel7-volume-1
        - name: drkiq-postgres
          persistentVolumeClaim:
            claimName: drkiq-postgres
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - postgresql-96-rhel7
        from:
          kind: ImageStreamTag
          name: postgresql-96-rhel7:latest
          namespace: myproject
        lastTriggeredImage: registry.access.redhat.com/rhscl/postgresql-96-rhel7@sha256:62a42216cb66e00cfcc66a28a6fb9a9953f2aed8592c4fd5140ddfa5b2193193
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 3
    labels:
      app: redis-32-rhel7
    name: redis-32-rhel7
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: redis-32-rhel7
      deploymentconfig: redis-32-rhel7
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: redis-32-rhel7
          deploymentconfig: redis-32-rhel7
      spec:
        containers:
        - image: registry.access.redhat.com/rhscl/redis-32-rhel7@sha256:166c2874ab917e0cee00f0dc4a5fa7a86febff38234c3b88ed7d657118ccf458
          imagePullPolicy: Always
          name: redis-32-rhel7
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/redis/data
            name: redis-32-rhel7-volume-1
          - mountPath: /var/lib/redis
            name: drkiq-redis
            subPath: data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: redis-32-rhel7-volume-1
        - name: drkiq-redis
          persistentVolumeClaim:
            claimName: drkiq-redis
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis-32-rhel7
        from:
          kind: ImageStreamTag
          name: redis-32-rhel7:latest
          namespace: myproject
        lastTriggeredImage: registry.access.redhat.com/rhscl/redis-32-rhel7@sha256:166c2874ab917e0cee00f0dc4a5fa7a86febff38234c3b88ed7d657118ccf458
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 3
    labels:
      app: sidekiq
    name: sidekiq
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: sidekiq
      deploymentconfig: sidekiq
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: sidekiq
          deploymentconfig: sidekiq
      spec:
        containers:
        - env:
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                key: DATABASE_URL
                name: drkiq.env
          - name: CACHE_URL
            valueFrom:
              configMapKeyRef:
                key: CACHE_URL
                name: drkiq.env
          - name: JOB_WORKER_URL
            valueFrom:
              configMapKeyRef:
                key: JOB_WORKER_URL
                name: drkiq.env
          - name: LISTEN_ON
            valueFrom:
              configMapKeyRef:
                key: LISTEN_ON
                name: drkiq.env
          - name: SECRET_TOKEN
            valueFrom:
              configMapKeyRef:
                key: SECRET_TOKEN
                name: drkiq.env
          - name: WORKER_PROCESSES
            valueFrom:
              configMapKeyRef:
                key: WORKER_PROCESSES
                name: drkiq.env
          image: 172.30.1.1:5000/myproject/sidekiq@sha256:19b85bfe31656eb02658b001c2fa8dc280d107ea2a22a71862efe849705793eb
          imagePullPolicy: Always
          name: sidekiq
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /drkiq/public
            name: sidekiq-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: sidekiq-volume-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - sidekiq
        from:
          kind: ImageStreamTag
          name: sidekiq:latest
          namespace: myproject
        lastTriggeredImage: 172.30.1.1:5000/myproject/sidekiq@sha256:19b85bfe31656eb02658b001c2fa8dc280d107ea2a22a71862efe849705793eb
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    generation: 1
    labels:
      build: drkiq
    name: drkiq
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/myproject/drkiq:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2018-09-11T15:51:46Z
    creationTimestamp: null
    generation: 2
    labels:
      app: postgresql-96-rhel7
    name: postgresql-96-rhel7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhscl/postgresql-96-rhel7
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/myproject/postgresql-96-rhel7:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2018-09-11T15:50:33Z
    creationTimestamp: null
    generation: 2
    labels:
      app: redis-32-rhel7
    name: redis-32-rhel7
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: registry.access.redhat.com/rhscl/redis-32-rhel7
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/myproject/redis-32-rhel7:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    generation: 1
    labels:
      build: sidekiq
    name: sidekiq
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/myproject/sidekiq:latest
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      app: drkiq
      build: drkiq
    name: drkiq
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: drkiq:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: Wek-BGVQqDSS31O9wHmy
      type: GitHub
    - generic:
        secret: HEd8CiWs1S1vtVACw3_V
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      app: sidekiq
      build: sidekiq
    name: sidekiq
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: sidekiq:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: RRQxUomu1gKdsszU4_d2
      type: GitHub
    - generic:
        secret: OB3H5G2OCm5ygcM3-jEV
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: drkiq
    name: drkiq
  spec:
    host: drkiq-myproject.192.168.99.100.nip.io
    to:
      kind: Service
      name: drkiq
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-09-11T17:20:27Z
        status: "True"
        type: Admitted
      host: drkiq-myproject.192.168.99.100.nip.io
      routerName: router
      wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: drkiq
    name: drkiq
  spec:
    ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: drkiq
      deploymentconfig: drkiq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: postgresql-96-rhel7
    name: postgresql-96-rhel7
  spec:
    ports:
    - name: 5432-tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgresql-96-rhel7
      deploymentconfig: postgresql-96-rhel7
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: redis-32-rhel7
    name: redis-32-rhel7
  spec:
    ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      app: redis-32-rhel7
      deploymentconfig: redis-32-rhel7
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
